In [ ]:
import torch

In [ ]:
x=torch.arange(12)

In [ ]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

In [ ]:
y=x.reshape(3,4)

In [ ]:
y.shape

torch.Size([3, 4])

In [ ]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.tensor([[1.9,2,3,4],[3,4,5,34]])

tensor([[ 1.9000,  2.0000,  3.0000,  4.0000],
        [ 3.0000,  4.0000,  5.0000, 34.0000]])

In [ ]:
x=torch.tensor([[1.0,2,3,8]])

In [ ]:
y=torch.tensor([[2,2,2,2]])

In [ ]:
x+y,x-y,x*y,x/y,x**y

(tensor([[ 3.,  4.,  5., 10.]]),
 tensor([[-1.,  0.,  1.,  6.]]),
 tensor([[ 2.,  4.,  6., 16.]]),
 tensor([[0.5000, 1.0000, 1.5000, 4.0000]]),
 tensor([[ 1.,  4.,  9., 64.]]))

In [ ]:
torch.cat((x,y),dim=0)

tensor([[1., 2., 3., 8.],
        [2., 2., 2., 2.]])

In [ ]:
torch.cat((x,y),dim=1)

tensor([[1., 2., 3., 8., 2., 2., 2., 2.]])

In [ ]:
x==y

tensor([[False,  True, False, False]])

In [ ]:
x.sum()

tensor(14.)

In [ ]:
x[0:1]

tensor([[1., 2., 3., 8.]])

In [ ]:
before=id(x)

In [ ]:
x=x+y

In [ ]:
id(y)==before

False

In [ ]:
x[:]

tensor([[ 3.,  4.,  5., 10.]])

In [ ]:
x[1:2:3]

tensor([], size=(0, 4))

In [ ]:
c=torch.tensor([3.5])

In [ ]:
c.item()

3.5

In [ ]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)

In [ ]:
data_file=os.path.join('..','data','house_tiny.csv')

In [ ]:
with open(data_file,'w') as f:
  f.write('NumRooms,Alley,Price\n')
  f.write('NA,Pave,127500\n')
  f.write('2,NA,17500\n')
  f.write('4,Pave,127500\n')
  f.write('4,NA,127500\n')
  
  
  


In [ ]:
import pandas as pd


In [ ]:
data=pd.read_csv(data_file)

In [ ]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN   17500
2       4.0  Pave  127500
3       4.0   NaN  127500

In [ ]:
inputs,outputs=data.iloc[:,:2],data.iloc[:,2]

In [ ]:
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0  Pave
3       4.0   NaN

In [ ]:
outputs

0    127500
1     17500
2    127500
3    127500
Name: Price, dtype: int64

In [ ]:
inputs=inputs.fillna(inputs.mean())

In [ ]:
inputs

NumRooms Alley
0  3.333333  Pave
1  2.000000   NaN
2  4.000000  Pave
3  4.000000   NaN

In [ ]:
inputs=pd.get_dummies(inputs,dummy_na=True)

In [ ]:
inputs

NumRooms  Alley_Pave  Alley_nan
0  3.333333           1          0
1  2.000000           0          1
2  4.000000           1          0
3  4.000000           0          1

In [ ]:
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)

In [ ]:
X,y

(tensor([[3.3333, 1.0000, 0.0000],
         [2.0000, 0.0000, 1.0000],
         [4.0000, 1.0000, 0.0000],
         [4.0000, 0.0000, 1.0000]], dtype=torch.float64),
 tensor([127500,  17500, 127500, 127500]))

In [ ]:
A=torch.arange(20,dtype=torch.float32).reshape(4,5)

In [ ]:
A

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [ ]:
B=A.clone()

In [ ]:
B

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [ ]:
A, A+B

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]))

In [ ]:
A*B

tensor([[  0.,   1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.,  81.],
        [100., 121., 144., 169., 196.],
        [225., 256., 289., 324., 361.]])

In [ ]:
X=torch.arange(24).reshape(2,3,4)

In [ ]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
a=2

In [ ]:
X+a

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [ ]:
X.sum()

tensor(276)

In [ ]:
X.sum(dim=[1,2],keepdim=True)

tensor([[[ 66]],

        [[210]]])

In [ ]:
X.cumsum(dim=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]])

In [ ]:
Z=torch.ones(4,)

In [ ]:
P=Z+3

In [ ]:
Z,P

(tensor([1., 1., 1., 1.]), tensor([4., 4., 4., 4.]))

In [ ]:
torch.dot(Z,P)

tensor(16.)

In [ ]:
torch.sum(Z*P)

tensor(16.)

In [ ]:
A.shape

torch.Size([4, 5])

In [ ]:
torch.mv(A.T,Z)

tensor([30., 34., 38., 42., 46.])

In [ ]:
torch.mm(A,B.T)

tensor([[  30.,   80.,  130.,  180.],
        [  80.,  255.,  430.,  605.],
        [ 130.,  430.,  730., 1030.],
        [ 180.,  605., 1030., 1455.]])

In [ ]:
torch.norm(A)

tensor(49.6991)

In [ ]:
torch.abs(A).sum()

tensor(190.)

In [ ]:
torch.norm(torch.ones((4,8)))

tensor(5.6569)

In [ ]:
torch.ones((2,5,4)).sum(dim=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
# 自动求导

In [ ]:
# y=2*XT*X

In [ ]:
x=torch.arange(4.0)

In [ ]:
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [ ]:
x.grad

In [ ]:
y=2*torch.dot(x,x)

In [ ]:
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [ ]:
y=x.sum()

In [ ]:
x.grad

tensor([0., 0., 0., 0.])

In [ ]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [ ]:
y=x*x

In [ ]:
y.sum().backward()

In [ ]:
x.grad

tensor([0., 2., 4., 6.])

In [ ]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x

z.sum().backward()

In [ ]:
x.grad==u

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [ ]:
# 计算图需要python控制流

In [ ]:
def f(a):
  b=a*2
  while b.norm() < 1000:
    b=b*2
  if b.sum() > 0:
    c = b
  else:
    c = 100*b
  return c

a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

a.grad == d/a

tensor(True)